### ISSUE TITLE
Cannot read property 'destroy' of undefined

### ISSUE THREAD

**Issue by akana** [zyra/ionic-tooltips#20]
Ionic version: (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] 2.x
[ x] 3.x
[ ] 4.x

I'm submitting a ... (check one with "x")
[x ] bug report
[ ] feature request

Browser : Chrome v.61.0.3163.100

**Steps to reproduce:**
- list item with tooltip
- quick mouse over on a lot of randoms item
- there's error below
ERROR TypeError: Cannot read property 'destroy' of undefined
    at tooltip.directive.js:174
    at t.invokeTask (polyfills.js:3)
    at Object.onInvokeTask (core.es5.js:4140)
    at t.invokeTask (polyfills.js:3)
    at r.runTask (polyfills.js:3)
    at invoke (polyfills.js:3)
    at n (polyfills.js:2)

**Comment by benjcallaghan** [comment]
+1 

I'm having this same issue with 2 or 3 buttons side-by-side that each have a "hover" tooltip.

**Comment by PAnd0** [comment]
+1

**Comment by salbahra** [comment]
Also seeing the same issue when using the hover event.

**Comment by ihadeed** [comment]
Fixed in `2.0.1`

**Comment by richie50** [comment]
@ihadeed i'm not sure about that fixed, i'm using the current version and i can still see it

**Comment by madoBaker** [comment]
this should be fixed with latest release. please confirm all is good
